import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import MaxWidthWrapper from "@/components/max-width-wrapper";
import Footer from "@/components/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`font-roboto bg-[#F6F7FB] bg-no-repeat min-h-screen relative`}>
				<MaxWidthWrapper>
					<Header />
					<main className="pb-20">{children}</main>
				</MaxWidthWrapper>
				<Footer />
			</body>
		</html>
	);
}
